# Site settings
title: Data Science | Resource
email: ziaulhaq@mhs.dinus.ac.id
description: > # baru belajar data science, sedikit menulis disini, berbagi kalau memang bisa dibaca ya, hehehe
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/datascience"
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: zhq41
github_username:  zhq41

# Build settings
markdown: redcarpet
pygments: true
